feat: Implement the API design and set up pyproject.toml for building wheel
foundation-model-stack/fm-training-estimator pull request #11
Opened 2024-10-24 05:00 UTC by aluu317

Run:
```
python3 -m build
```
to build a wheel

Then install it:
```
pip3 install .
```

And run the sdk example:
```
python3 fm_training_estimator/sdk/examples/ex1.py
```

This PR:
-  exposes 3 more estimate functions in sdk for a total of 4 estimate functions: memory, cost, time, tokens
- changes some print statements to logging
- updates the SDK example code

2024-10-24 09:59 UTC, ChanderG reviewed
I will need to test out the various UI's once (no integration tests yet!) to be fully sure about some of the changes, but looks good otherwise.

2024-10-24 09:59 UTC, ChanderG commented on fm_training_estimator/ui/core.py
> +    return res
Is this needed?

2024-10-24 09:59 UTC, ChanderG commented on fm_training_estimator/config/arguments.py
> +        default=0,
I think changing the default to 0 (which is auto-discover num gpus) is a good idea. But not sure if this is clear in the API, or how we should document this. (I myself got confused when typing up this comment if 0 or -1 meant auto-discover :-) )

2024-10-24 22:42 UTC, aluu317 commented on fm_training_estimator/config/arguments.py
> +        default=0,
This is cool, i didn't know actually that one of them is for auto-discovery. I think it's 0, [here](https://github.com/foundation-model-stack/fm-training-estimator/blob/main/fm_training_estimator/memory/hybrid/hybrid.py#L58)

2024-10-24 22:44 UTC, aluu317 commented on fm_training_estimator/ui/core.py
> +    return res
oops sorry, i was debugging, removing

2024-10-24 22:47 UTC, aluu317 commented on fm_training_estimator/throughput/hybrid/hybrid.py
> +            "method": "fsdp"
@ChanderG I wasn't sure about this. I saw that the `data.csv` file you gave me didn't have any "full" in the `method` column so I assumed maybe we are looking for "fsdp". Should I leave it as `self.fm.technique.value` which is `full`, or should this code be ok?

2024-10-28 10:16 UTC, ChanderG commented on fm_training_estimator/throughput/hybrid/hybrid.py
> +            "method": "fsdp"
We should remove the if condition and pass in technique as-is.

I only recently changed the frontend UI to display "full" instead of "fsdp". We can fix this mismatch either in the data.csv file, or in the web ui frontend. Most likely in the source data files, since "fsdp" is misleading when both are fsdp.

2024-10-28 10:24 UTC, ChanderG requested changes
I was testing the UI with the new changes and ran into a problem. This is in the "parse" function interface which you don't need for the SDK code as it stands (the user is expected to put together the config components directly in Python), but is needed in the other interfaces (UI/cli) where the input is parsed out of JSON.

Here is a minimal reproducer:
```
from enum import Enum
from transformers import HfArgumentParser
from dataclasses import dataclass, field

class TuningTechnique(Enum):
    LORA = "lora"
    FULL = "full"

@dataclass
class FMArguments:
    technique: TuningTechnique = field(
        default=TuningTechnique.FULL,
        metadata={"help": ("Fine-tuning technique being used")},
    )

config = {"technique": "lora"}
arg_parser = HfArgumentParser([FMArguments])
res = arg_parser.parse_dict(config)

print(res)
```
We expect the result to be a parsed FMArguments object, with the field technique an enum, but instead we get the technique field set to a string.

I think this is a limitation of HF Argparser (https://github.com/huggingface/transformers/blob/main/src/transformers/hf_argparser.py) in that it may not be possible to parse out from dict to enum like we would want.

2024-10-28 21:04 UTC, aluu317 commented
@ChanderG Ahh good catch, I see the problem. I spent some time today trying to figure out how to get enum to work with JSON/dict parsing, but couldn't. So I switched it back to using str. Let me know if this is good to merge!

2024-10-29 09:03 UTC, ChanderG approved these changes
LGTM.

2024-10-29 09:04 UTC, merged